# Generated by Django 3.0.3 on 2020-04-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0005_auto_20200410_0604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
